add completion installation script

diff --git a/shell/ffd b/shell/ffd
--- a/shell/ffd
+++ b/shell/ffd
@@ -8,7 +8,8 @@ do
     H)
       options+=(-H)
       ;;
-    *) echo "Invalid option: $OPTARG" 1>&2
+    *)
+      echo "Invalid option: $OPTARG" 1>&2
       ;;
   esac
 done
